server:
  port: 8083

spring:
  application:
    name: tracking-service

  data:
    mongodb:
      uri: mongodb://${MONGO_USER:dev}:${MONGO_PASSWORD:devpass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/tracking_db?authSource=admin

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:devpass}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: tracking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
