server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/payment_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:devpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

jwt:
  signerKey: "${JWT_SIGNER_KEY:BcGAKAxY7nEWT4lOBlPMxo4lgdgurBlEuL5wlzxqSuUauQI5+2G6I6A6KRe38XhF}"
