name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ci:
    name: Build & Test — ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - gateway-api
          - identity-service
          - profile-service
          - order-service
          - payment-service
          - tracking-service
          - notification-service
          - hub-and-branch-service
          - staff-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          cache: maven

      - name: Build & Test
        working-directory: services/${{ matrix.service }}
        run: mvn clean verify -B
